### ISSUE TITLE
add version information to .rosinstall with optional argument --add-version

### ISSUE THREAD

**Issue by karlkurzer** [vcstools/wstool#103]
I think it would be great to add the version information to the .rosinstall.

When working on larger projects with many different repositories it would be great, if I could send my .rosinstall to a colleague, so that he can pull the exact versions I have currently checked out.

IMHO it should be done with an optional argument working with both the update as well as the scrape command like this: `wstool update --add-version` or `wstool scrape --add-version`

**Comment by rsinnet** [comment]
The feature to generate a .rosinstall with version info already exists as the `export` command and with the `--exact` option. It was added in PR #98. Please let me know if this feature is incomplete.

**Comment by karlkurzer** [comment]
I see, thanks for the info. Will there be a release of 1.14 soon?

**Comment by wjwwood** [comment]
Not sure, I'll try to have a look at the backlog and make a new release soon.
