### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by v4hn** [vcstools/wstool#105]
The last release happened more than a year ago and there have been a number of changes, including the [snapshot command](https://github.com/vcstools/wstool/commit/79df9479d9f3eccc51c9e2e0af339c5930cf464f) that sounds quite nice.

How about a new release?

**Comment by v4hn** [comment]
friendly ping.

**Comment by tkruse** [comment]
@wjwwood : you need some unfriendly ping to comment?
Possibly if  @jayvbd is planning on making multiple PRs in the near future a release could wait for that...

**Comment by jayvdb** [comment]
Yup, I've got two prs to launch. I need a few days max.

**Comment by wjwwood** [comment]
Friendly or not, pings don't magically give me more time to work on this stuff, but I do appreciate the pr reviews and iterating with people on the issues.

I just released `0.1.16` in preparation for Melodic.
