### ISSUE TITLE
Support directory move

### ISSUE THREAD

**Issue by jayvdb** [vcstools/wstool#109]
If I move a directory and run `wstool scrape`, it will add a second entry to `.rosinstall`.

It would be nice if there was a `wstool mv from to`, or `wstool scrape` checked for an existing entry with the same remote name, emitted a warning and did a move if the user confirms that is what was intended.

**Comment by tkruse** [comment]
Should be sufficient if scrape detected configured repositories that are missing from filesystem and offered to remove those I guess. That should be easier to implement and have the same effect, covering other usecases as well.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
