### ISSUE TITLE
OSError duplicated in foreach when repo hasnt been updated

### ISSUE THREAD

**Issue by jayvdb** [vcstools/wstool#110]
If a repository hasnt been fetched/updated, `foreach` will result in two (or three) error reports that say the same thing.

```
ERROR [vcstools] Command failed with OSError. 'git foo' <True, /path/to/missing/repo>:
[Errno 2] No such file or directory: '/path/to/missing/repo'[/vcstools]
....
Error processing 'local-name' : u"Command failed with OSError. 'git foo' <True, /path/to/missing/repo>:\n[Errno 2] No such file or directory: '/path/to/missing/repo'"
```

**Comment by tkruse** [comment]
Can you give a more complete example with the command?

Probably not severe enough as a bug/improvement to implement a PR, but if anyone touches the code, might as well look into this.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
