### ISSUE TITLE
Ignore and update changed URIs

### ISSUE THREAD

**Issue by jayvdb** [vcstools/wstool#111]
`wstool up` has lots of options to handle changed URIs, but the two I am most interested are missing.

The most important is to ignore the fact that the URI is different; I happen to know that they are different URIs to the same repo, often with `.git` at the end, or switched to ssh vs http etc.

Another is to update the repo config's URI to match the `.rosinstall` URI.

**Comment by tkruse** [comment]
Can you explain more why this is not sufficiently well supported by
manually changing the .rosinstall or the repo configuration?

Those seem to be one-off tasks, and even if wstool had those features, most
users would probably not know and make such changes manually anyway, the
one time in their lives they need to.

**Comment by jayvdb** [comment]
Firstly, this has nothing to do with changing the `.rosinstall`.

Sometimes I have different remotes in some of my repositories, like if I have had to switch to ssh, temporarily.
I dont want to backup, as I know that my altered URI may be strictly different, but it is either semantically identical, or it differs only by protocol, in which case it is logically identical.

It would be nice to be able to overwrite (update) those remotes to be the same as `.rosinstall`.  A sync operation.  Effectively the oppose of a scrape.

Or, rather than touch the local repository's config, `up` could (if instructed by the user) ignore the fact they are different and attempt to use the different URI.

**Comment by tkruse** [comment]
Maybe we can also consider extending the comparison,  so that ssh and non ssh are considered equal. Could that solve your problems?

**Comment by jayvdb** [comment]
Doesnt solve my "update" request, forcing `.rosinstall` URIs into the repos.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
