### ISSUE TITLE
Improve URI similarity checks

### ISSUE THREAD

**Issue by jayvdb** [vcstools/wstool#112]
Spawning from https://github.com/vcstools/wstool/issues/111#issuecomment-345862810 , a hosted repository can have several URIs which are used for different purposes.  The most common is different protocols , but often `../foo` can have a trailing `.git` like `../foo.git`.

It would be good to have some warnings in place when the `.rosinstall` URI and local copy URI are considered equivalent.

Additionally, ideally there is a way to syncronise the two, either
1. updating the `.rosinstall`.  Possibly a `scape` enhancement?
2. overwriting the URI in the repository.  Destructive; much less simple, and I suspect due to https://github.com/vcstools/vcstools/issues/126 that there will be problems wrt to local copies which have multiple remotes.

**Comment by tkruse** [comment]
At a glance, to consider syntactically different urls as semantically same, a PR should change url_matches function in vcstools in
https://github.com/vcstools/vcstools/blob/master/src/vcstools/vcs_base.py
or respective subclasses for things like a .git suffix.

The addition to `scrape` would be slightly more involved, we'd have to verify for all registered repos if the .rosinstall information and the actual configuration match, and if not call cmd_set for all where it does not match
https://github.com/vcstools/wstool/blob/master/src/wstool/multiproject_cli.py

I cannot tell exactly how little or much effort this would be.

I think both changes might be useful enough and not too risky to merge later on.

I fear you might not get any other feedback than mine about this (or your other recently added issues), but feel free to directly ping users wjwood or tfoote if you do have the time to implement the PRs yourself and want more feedback for the preparation.

**Comment by wjwwood** [comment]
The benefit sounds reasonable, but as @tkruse said, our time is pretty limited so at best I could comment on technical proposals briefly and review pr's eventually.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
