### ISSUE TITLE
Allow wstool foreach commands to access state

### ISSUE THREAD

**Issue by jayvdb** [vcstools/wstool#113]
`foreach` commands should be able to access the internal wstool variables, such as the root directory of the workspace , and the items being iterated over : the scmtype, local-name and uri.

Currently a wstool foreach command needs to do `wstool info . --only scmtype,localname,uri` to get this information, and separately `wstool info --root` if it doesnt want to derive the root from the localname.

This should be done using substitution variables in the command line, so that non-ros-aware commands can be used with wstool; .e.g

`wstool foreach --git git clone -o upstream "{uri}" "{localname}"`

(That solves https://github.com/vcstools/wstool/issues/59 ;-)

A simpler solution is to stuff this information into `ROS_*` environment variables, so that ros-aware tools can easily obtain these values without invoking `wstool info`

**Comment by tkruse** [comment]
Not sure how this would solve #59, but in general the idea sounds ok. Not sure if many people would use this though, so if you don't do the pr, nobody might

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
