### ISSUE TITLE
wstool 0.1.16-1 deb packages seem broken

### ISSUE THREAD

**Issue by pbeeson** [vcstools/wstool#116]
I got back in the office this AM from a week out and ran a normal apt-get update/upgrade.  Afterwards, rosinstall stopped working.  I was able to force install python-wstools 0.1.12 using synaptic, and things work fine, so something is wrong with the 0.1.16 debian package.  This is the case on EVERY 16.04/kinetic machine I've tested.

```
pbeeson@tardis:/usr/bin$ rosws
Command requires a target workspace.
rosws is a command to manipulate ROS workspaces. rosws replaces its predecessor rosinstall.

Official usage:
  rosws CMD [ARGS] [OPTIONS]

rosws will try to infer install path from context

Type 'rosws help' for usage.

help         	provide help for commands
init         	set up a directory as workspace

set          	add or changes one entry from your workspace config
merge        	merges your workspace with another config set
remove (rm)   	remove an entry from your workspace config, without deleting files
scrape       	interactively add all found unmanaged VCS subfolders to workspace

update (up)   	update or check out some of your config elements

info         	Overview of some entries
status (st)   	print the change status of files in some SCM controlled entries
diff (di)    	print a diff over some SCM controlled entries
foreach      	run shell command in given entries

regenerate   	create ROS workspace specific setup files
pbeeson@tardis:/usr/bin$ sudo apt-get install python-wstool
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be upgraded:
  python-wstool
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/43.4 kB of archives.
After this operation, 57.3 kB of additional disk space will be used.
(Reading database ... 456588 files and directories currently installed.)
Preparing to unpack .../python-wstool_0.1.16-1_all.deb ...
Unpacking python-wstool (0.1.16-1) over (0.1.12-1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up python-wstool (0.1.16-1) ...
pbeeson@tardis:/usr/bin$ rosws
Traceback (most recent call last):
  File "/usr/bin/rosws", line 52, in <module>
    import rosinstall.rosws_cli
  File "/usr/lib/python2.7/dist-packages/rosinstall/__init__.py", line 33, in <module>
    import wstool.helpers
  File "/usr/lib/python2.7/dist-packages/wstool/helpers.py", line 37, in <module>
    from wstool.config_elements import SetupConfigElement
  File "/usr/lib/python2.7/dist-packages/wstool/config_elements.py", line 43, in <module>
    from wstool.config_yaml import PathSpec
  File "/usr/lib/python2.7/dist-packages/wstool/config_yaml.py", line 37, in <module>
    import wstool.config
  File "/usr/lib/python2.7/dist-packages/wstool/config.py", line 35, in <module>
    from wstool.config_elements import AVCSConfigElement, OtherConfigElement, SetupConfigElement
ImportError: cannot import name AVCSConfigElement
```

**Comment by rsinnet** [comment]
@pbeeson As I understand it, `rosws` was long ago deprecated in favor of `wstool`.

**Comment by wjwwood** [comment]
I'm looking into it.

> @pbeeson As I understand it, rosws was long ago deprecated in favor of wstool.

Should still work though.

**Comment by poggenhans** [comment]
Same isse here. There is a cyclic dependency between `config_yaml.py` and `config_element.py`. Just import either of them and you will see it.

For reasons beyond me, if `config.py` is imported first, everything is fine. This is why the issue does not show when executing `wstool`.

**Comment by pbeeson** [comment]
Yes wstool works, but rosws does not.  

@rsinnet I have legacy systems with clients that use old scripts, so I have unit tests and scripts that stay in sync with those deployed systems.  I could try to push script changes to all those machines, but some machines I only get remote access to rare occasions.  It would be much better if the legacy tools didn't break.

**Comment by wjwwood** [comment]
I just released `0.1.17` (should be in public debs soon, pip now) and that should fix the issue.

**Comment by pbeeson** [comment]
Great!

And as per suggestion of @rsinnet, I made the (less painful than originally thought) change and push to all my customer's deployed systems so that we can now pull the latest ros/Ubuntu updates without issue.

**Comment by tkruse** [comment]
rosws was not deprecated as such, it is related to rosbuild and creates `setup.sh` files. wstool is for catkin. Not sure how many people still use rosbuild / rosws, might be an idea to do a community survey and deprecate for good.
