### ISSUE TITLE
Sort info output

### ISSUE THREAD

**Issue by orzechow** [vcstools/wstool#122]
It would be very handy if the table printed by `wstool info` would be sorted by package name.  
I work with >100 packages in my workspace, so sorting is a must for me...

Yes, I can use `wstool info | sort` instead, but that distroys the prefix and table header (no big issue though).

**Comment by tkruse** [comment]
At a glance, I guess this was not considered because the package order has important semantic meaning in with rosbuild in the ROS_PKG_PATH, and wstool and rosinstall/rosws share the same library code. Sorting in wstool exclusively could be useful, I guess.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
