### ISSUE TITLE
Add option to "scrape" to also set versions

### ISSUE THREAD

**Issue by pjreed** [vcstools/wstool#124]
Currently, the `scrape` verb does not set a version on a repository when adding it to a workspace file, which means that workspaces created or updated from that file will use the default branch for that repository.  This is a little annoying if your workspace is using tagged versions of certain repositories or if you are intentionally making a workspace that uses development branches.

It would be very useful if there was a flag that would also cause `scrape` to set the versions for newly-added repositories to their current version, and maybe also another option that would also change the versions for repositories that already exist in the file.

**Comment by tkruse** [comment]
As you point out, there are multiple alternatives for setting the 'version' attribute of the workspace, such as choosing an alternative branch versus a fixed version (and this is just for git, I assume). Do you have a more detailed suggestion for how to present this to the user?

**Comment by pjreed** [comment]
There are probably a lot of potential alternatives, but for me, by far the most common use case would be to se the `version` to whatever the currently set version in the repository's directory.  I could also see it being useful to manually specify the version for newly-added repositories.  Something like:

```
$ wstool scrape -h
Usage: wstool scrape [OPTIONS]

interactively add all found unmanaged VCS subfolders to workspace

Options:
  -h, --help            show this help message and exit
  -y, --confirm         Do not ask for confirmation
  -t WORKSPACE, --target-workspace=WORKSPACE
                        which workspace to use
  -c, --current         set new VCS's versions in the
                        workspace file to their current versions
  -v VERSION, --version=VERSION
                        set new VCS's versions in the 
                        workspace file to VERSION

See: http://www.ros.org/wiki/rosinstall for details
```

Switching versions for existing workspace entries might be more appropriate for the `set` verb.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
