### ISSUE TITLE
--user install is broken

### ISSUE THREAD

**Issue by ibtaylor** [vcstools/wstool#126]
```shell
pip install --user wstool
```
no longer works
```
    copying completion/wstool-completion.bash -> /etc/bash_completion.d
    error: [Errno 13] Permission denied: '/etc/bash_completion.d/wstool-completion.bash'
```

This affects versions `0.1.17` `0.1.16` `0.1.15` `0.1.14`.. 

On a side-note, I think it's a little weird to "re-release" a version. The world has already tested and signed off on a particular version working properly, but now you've changed what that means. Seems like a reason to use patch version numbering.

**Comment by tfoote** [comment]
> On a side-note, I think it's a little weird to "re-release" a version. The world has already tested and signed off on a particular version working properly, but now you've changed what that means. Seems like a reason to use patch version numbering.

I agree that changing tags is generally not a good idea. Can you explain what version you think has been "re-released". There does not appear to have been any retagging or rereleasing of this project.

**Comment by ibtaylor** [comment]
https://github.com/vcstools/wstool/releases the versions I listed seemed to be all from the same day. Cached versions of the package did not seem to have the issue so I guess I assumed some rereleases had occured. If not, my mistake.

**Comment by ibtaylor** [comment]
@tfoote I'm not sure what's going on with the failures in #127 

The change fixes the issue for me.
`pip install --user wstool` runs `setup.py` with `--prefix=` but sense an empty string in python evaluates to `False`, it's choosing `sys.prefix` in the expression `opts.prefix or sys.prefix`
