### ISSUE TITLE
How to select a single package within git repository with `wstool`

### ISSUE THREAD

**Issue by flplv** [vcstools/wstool#129]
Imagine this git repository:

```
my_git_repository_folder
+ ros_package_a
+ ros_package_b
+ README.md
```

Now I want to `wstool` to load only `package_a` into my workspace. How can I achieve that?

**Comment by wjwwood** [comment]
Git and other distributed VCS do not allow for partial checkouts, so wstool does not support this as far as I know.

This is part of the role of a release repository, which takes each package and puts it on it's own branch, re-rooted to be just the package without its peers.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
