### ISSUE TITLE
Errors extracting tarballs from github (recent change?)

### ISSUE THREAD

**Issue by gavanderhoorn** [vcstools/wstool#130]
Just ran into this myself -- after reading/discussion about this on ROS Answers in [#q314827](https://answers.ros.org/question/314827) and [#q315325](https://answers.ros.org/question/315325): `wstool` fails to extract *some* tarballs from Github when the `.rosinstall` file specs tarballs.

Errors are similar to the following (taken from [#q314827](https://answers.ros.org/question/314827)):

```
ERROR [vcstools] Tarball download unpack failed: "geometry2-release-release-kinetic-tf2_msgs-0.5.20-0 is not a subdirectory with contents in members ['geometry2-release-release-kinetic-tf2_msgs']"[/vcstools]
```

At first I thought it could be #125, but after manually downloading the archive and inspecting it, it seems there is no version suffix on the directory contained within it (so archive contains `geometry2-release-release-kinetic-tf2_msgs`, instead of `geometry2-release-release-kinetic-tf2_msgs-0.5.20-0`).

OPs of both ROS Answers questions seem to report seeing similar problems.

---

This seems similar to ros/geometry2#306, but there the name of the repository changed.

**Comment by chrisl8** [comment]
Yes, I am the OP of [#q315325](https://answers.ros.org/question/315325)

Just repeating what I found in my research, I can "fix" the issue temporarily by running these lines **AFTER** `rosinstall_generator` but **BEFORE** `wstool` allowed me to finish the process:

```
sed -i 's/version: \(ros_comm-release-release-melodic-ros_comm\)-[0-9\.\-]\+/version: \1/g' melodic-desktop-full.rosinstall
sed -i 's/version: \(ros_comm-release-release-melodic-rosbag_storage\)-[0-9\.\-]\+/version: \1/g' melodic-desktop-full.rosinstall
sed -i 's/version: \(ros_comm-release-release-melodic-rosgraph\)-[0-9\.\-]\+/version: \1/g' melodic-desktop-full.rosinstall
```

Let me know if there is any further testing I can do for you to help fix this or further data I can provide to help narrow down the issue.

**Comment by tkruse** [comment]
So if GitHub does not care about this bug, we could look into making the wstool code flexible. It would not be that complex to allow the subfolder name to be either versioned or not.

**Comment by KenYN** [comment]
And I am the OP of [#314827](https://answers.ros.org/question/314827).

My fix is now at:

    green=`tput setaf 2`
    reset=`tput sgr0`
    # Version information is broken in these projects
    for brokenVersion in \
            bond_core-release-release-$1-smclib \
            dynamic_reconfigure-release-release-$1-dynamic_reconfigure \
            genmsg-release-release-$1-genmsg \
            geometry_angles_utils-release-release-$1-angles \
            geometry2-release-release-$1-tf2_eigen \
            geometry2-release-release-$1-tf2_geometry_msgs \
            geometry2-release-release-$1-tf2_msgs \
            image_common-release-release-$1-camera_calibration_parsers \
            ros_comm-release-release-$1-rosmaster \
            ros_comm-release-release-$1-rosmsg \
            ros_comm-release-release-$1-roswtf \
            ; do
        echo "Updating broken ${green}${brokenVersion}${reset} version number information"
        sed -i 's/version: \('$brokenVersion'\)-[0-9\.\-]\+/version: \1/g' $output_file
    done

Where `$1` is `kinetic`.

**Comment by chrisl8** [comment]
Since the list of affected packages changes daily, "fixing" wstool seems like the only option.

I am not familiar with the tool at all, but if somebody wants to point me to the code where the changes would be made I can take a stab at a patch and a pull request.
Unless somebody else is already working on this.

**Comment by gavanderhoorn** [comment]
@chrisl8 wrote:
> Since the list of affected packages changes daily, "fixing" wstool seems like the only option.

I would think the first course of action would be to inquire with Github why they are seemingly "randomly" appending/not appending version specs to the directories in the tarballs downloaded from their servers.

Everything else would seem to be work-arounds right now.

Root cause analysis seems more appropriate.

**Comment by clalancette** [comment]
FWIW, this issue is being tracked (with a lot more detail) over on vcstools: https://github.com/vcstools/vcstools/issues/147

**Comment by gavanderhoorn** [comment]
Closing this one then, as it's essentially a duplicate.

Thanks @clalancette.

**Comment by KenYN** [comment]
`image_common-release-release-kinetic-camera_calibration_parsers`, which was broken yesterday, is working today... :angry:

**Comment by gavanderhoorn** [comment]
Complain to GH :frowning_face:

**Comment by tkruse** [comment]
Sorry, I only saw messages on smartphone, else I could have linked to [vcstools/vcstools#147](https://github.com/vcstools/vcstools/issues/147) earlier.

**Comment by gavanderhoorn** [comment]
np @tkruse.

**Comment by KenYN** [comment]
I've had a go at fixing this in vcstools: https://github.com/KenYN/vcstools/commit/ddcfacb7dd10429ff5e57845d18657c8f1dc2997
