### ISSUE TITLE
Feature Request: Add --tags option to export command

### ISSUE THREAD

**Issue by rsinnet** [vcstools/wstool#131]
# Feature Request

Currently, the `export` command has two options (`--exact` and `--spec`) which control which versions are set in the generated `.rosinstall`. These options do NOT, however, allow capturing of the latest tag. This would be useful to capture a reference that will include future hot fixes and back-ported patches.

## Proposal
There are several versioning systems, but I think implementing just Git would be a starting point.

I propose we add the `--tags` option to the export commmand. This could do something like:
```
git describe --abbrev=0 --tags SOME_HASH
```
Using this with or without the `--spec` option would give specify which reference to pass to the above command.

But we have a bit of ambiguity that needs to be resolved, but not all repositories have tags. I think the only way to make this command practically useful is to assume any repository with a tag should use the tag. This may not work for everyone's use case but the problem becomes much more difficult if this is allowed to be set on a case-by-case basis.

As far as repositories that don't have tags, a fallback behavior is needed. I propose that this behavior function based on the presence of `--spec` and `--exact`.

**Comment by rsinnet** [comment]
Would love to get some feedback on this. I'm planning to either implement myself or have someone else at  https://github.com/MisoRobotics implement this in the next week or so.

**Comment by tkruse** [comment]
Can you given an example of the final command?
If I have these repositories (A, B ,C) with given commits and tags (rightmost is latest commit, tags in brackets):

    A: a0 -> a1 -> a2 -> a3
    B: b0 -> b1 -> b2[1.0] -> b3 -> b4
    C: c0 -> c1[1.0] -> c2 -> c3 [1.0]

Can you give some example(s) of how the new option would resolve differently from what the export command does now?

**Comment by rsinnet** [comment]
Great idea, I'll put a few examples together and post.

**Comment by rsinnet** [comment]
@tkruse , I've put together a sample repository that demonstrates what the expected output would be. Hopefully this should make the intention clear. Let me know what you think.

https://github.com/rsinnet/wstool-export-tags-example

**Comment by tkruse** [comment]
So it seems to me that --spec arguably contradicts --exact, because a git tag is arguably not as precise as an sha-id. Tags can change.
Also it seems to directly contradict --spec, since it looks at the repository, not at the spec. And in the case of multiple repositories, it would be quite difficult for users to tell whether the output is what they wanted or not. Any tag in any repo that the user forgot exists would influence the output. To me it seems the use case can be solved adequately and safer by the current behavior, where users can then manually modify the output.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
