### ISSUE TITLE
wstool vs vcstool

### ISSUE THREAD

**Issue by LucidOne** [vcstools/wstool#132]
Is there any benefits to wstool vs [vcstool](https://github.com/dirk-thomas/vcstool)?
Which one would be suggested for new projects?

Thanks!

**Comment by tkruse** [comment]
Functionally they cover very similar use cases.
See earlier discussions like

* https://github.com/vcstools/wstool/issues/19
* http://ros-users.122217.n3.nabble.com/Discourse-ros-org-General-File-naming-convention-quot-rosinstall-quot-misleading-td4030322.html

It is difficult to give an objective recommendation, it depends a bit on your situation. vcstool gets more support attention by OSRF, and is OSRFs choice for ROS2 projects. wstool may be safer to use with novice users in classroom settings.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
