### ISSUE TITLE
wstool: how to “push” updates using wstool

### ISSUE THREAD

**Issue by santhoshht** [vcstools/wstool#145]
Hello,

I want to use this tool as version control for our work space. I tested all the option provided in this tool. But i didn't find an option to push my local changes to remote location. Is there any way to push updates?

Thank you.

**Comment by tkruse** [comment]
There is no command to commit or to push (or to create new branch and tag). You could consider a command multiplexer instead, like https://github.com/dirk-thomas/vcstool, or any of those specialized on git only like https://github.com/inventhouse/allgit.

There are 2 main justifications:
* wstool is intended to be a safe tool preventing novice users from shooting themselves in the foot
* wstool is a VCS abstraction, not a command multiplexer, and finding a safe abstraction of commit/push that is semantically same for git, mercurial, svn and bzr is very tough.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
