### ISSUE TITLE
FReq:  `wstool merge` should perform init if .rosinstall doesn't already exist.

### ISSUE THREAD

**Issue by catskul** [vcstools/wstool#21]
`rosinstall` allowed initialization with a .rosinstall file

`wstool init` does not, and `wstool merge` will not function without `wstool init` first which itself only creates an empty file.

`wstool merge` should create the .rosinstall file if it doesn't already exist.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
