### ISSUE TITLE
Shell completion in wstool

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#32]
I'd like to add shell completion to wstool.
What is the best way to add this feature?
Do you have any idea?

**Comment by tkruse** [comment]
Hi Kentaro,

wstool commands are the same as rosws, except for options like --catkin

So the code should be the same as in
https://github.com/vcstools/rosinstall_tab_completion
for rosws, only last line needs changing and invalid option removed.

I cannot remember why wstool does not already have completion.

Maybe by now there is a better way know to package completion, William
might know. If not, a wstool_bash_completion project could be created to
release/install with pip.

**Comment by tkruse** [comment]
The files to copy and adapt are rosws.bash and rosws.zsh only

**Comment by tkruse** [comment]
Sorry, I once already started completion for wstool at
https://github.com/tkruse/wstool_catkin as env hook for catkin.
But I cannot remember if that works well or not.

I am traveling right now and cannot help more.

**Comment by wkentaro** [comment]
It works! thanks.

I think this feature should be installed as default pkg, because this is
very useful.
wstool is not only for ROS user, and if wstool_catkin does not depend ROS
environment (by making some changes),
I think it is better to add wstool_catkin to wstool. Is that possible? (you
may reply after the trip)

> I am traveling right now and cannot help more.
I see. I will wait for the end.

On Fri, Jun 19, 2015 at 10:58 AM, Thibault Kruse <notifications@github.com>
wrote:

> Sorry, I once already started completion for wstool at
> https://github.com/tkruse/wstool_catkin as env hook for catkin.
> But I cannot remember if that works well or not.
>
> I am traveling right now and cannot help more.
>
> On Jun 19, 2015 9:29 AM, "Thibault Kruse" <tibokruse@googlemail.com>
> wrote:
>
> > The files to copy and adapt are rosws.bash and rosws.zsh only
> > On Jun 19, 2015 9:27 AM, "Thibault Kruse" <tibokruse@googlemail.com>
> > wrote:
> >
> >> Hi Kentaro,
> >>
> >> wstool commands are the same as rosws, except for options like --catkin
> >>
> >> So the code should be the same as in
> >> https://github.com/vcstools/rosinstall_tab_completion
> >> for rosws, only last line needs changing and invalid option removed.
> >>
> >> I cannot remember why wstool does not already have completion.
> >>
> >> Maybe by now there is a better way know to package completion, William
> >> might know. If not, a wstool_bash_completion project could be created to
> >> release/install with pip.
> >> On Jun 18, 2015 2:46 PM, "Kentaro Wada" <notifications@github.com>
> wrote:
> >>
> >>> I'd like to add shell completion to wstool.
> >>> What is the best way to add this feature.
> >>>
> >>> —
> >>> Reply to this email directly or view it on GitHub
> >>> <https://github.com/vcstools/wstool/issues/32>.
> >>>
> >>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcstools/wstool/issues/32#issuecomment-113339821>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by tkruse** [comment]
As I said, one simple way would be to create a pipy package
wstool_tab_completion similar as for rosinstall.

The main problem with providing the completion together with wstool was
that different operating systems handle completion scripts differently.
This was 2 years ago.

Not sure if there is a good solution today.

**Comment by wkentaro** [comment]
Why not adding completion features to this repository like https://github.com/catkin/catkin_tools ?
I'm thinking to sendi PR with this commit. 
https://github.com/wkentaro/wstool/commit/f3aa9ffb4951f5339777f088bd94f76ca59dae24

**Comment by tkruse** [comment]
Yes, that seems okay at a glance. A bit hacky, but if accepted for catkin
tools, i won't object for wstool.

**Comment by wjwwood** [comment]
Sorry, I'm late to the party. I agree that the way `catkin_tools` distributes it's completion files is pretty hacky, but that's the best could come up with through my testing. I'd be more than willing to change how it's done in `catkin_tools` if there is a known better practice.

@wkentaro The commit you linked to should work, and is what I would suggest you do unless you find a better way to do it.

**Comment by tkruse** [comment]
It would be nice if all tools packaged with setuptools used the same code
for this. But creating a library to depend on might be overkill. Still it
would be possible to either cross reference the setup files, or to set up
and reference a template project. That way, if a bug or improvement is
found, it has better chances of propagating to all projects providing bash
completion via setuptools.

I am concerned mainly if this breaks installation on less tested platforms
like windows or bsd.
If that has been confirmed to be a non-issue for catkin_tools, my concerns
are satisfied.

**Comment by wjwwood** [comment]
I think this can be closed.
