### ISSUE TITLE
Diff with tracking remote branch?

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#34]
As feature proposal,
with `wstool info`, I'd like to know diff with remote tracking branch.

**Comment by tkruse** [comment]
Hello Kentaro, can you clarify by giving an example? Say the current output was:
```
$ wstool info
workspace: /home/kruset/work/ros/wstool_test

 Localname S SCM  Version-Spec UID  (Spec)  URI  (Spec) [http(s)://...]
 --------- - ---- ------------ -----------  ---------------------------
 vcstools    git  master       6435729d6a00 git@github.com:vcstools/vcstools.git
```

**Comment by tkruse** [comment]
I assume the suggestion is to return something like the UID for git, or the revision number for svn, etc.

It could help if you can motivate your request more, like pointing out what in your work would be made easier if you had this feature.

A change like this would at first require a change to the vcstools library, the class VcsClient in vcs_abstraction.py would require an extension like get_remote_version(self), which would then be implemented in different ways for each of the supported version control systems. If you want to help, you could research for each version control system the sequence of commands that need to be run, or even implement a PR.

**Comment by wkentaro** [comment]
I mean this kind of feature.
```
$ wstool info
workspace: /home/kruset/work/ros/wstool_test

 Localname S SCM  Version-Spec Tracking-Branch UID  (Spec)  URI  (Spec) [http(s)://...]
 --------- - ---- ------------ --------------- -----------  ---------------------------
 vcstools  C git  master       origin/master   6435729d6a00 git@github.com:vcstools/vcstools.git


$ wstool info --help
...
The Status (S) column shows
 x  for missing
 L  for uncommited (local) changes
 V  for difference in version and/or remote URI
 C  for difference with version and its tracking branch
```

With `git`, the remote tracking branch is gotten by `git config.[Version-Spec].remote` like 
```
git branch -vv --no-color  | grep "[*, ] master"
* master 7d480a9 [origin/master] new GitInfo type
```

**Comment by tkruse** [comment]
ok, so just an additional status flag would do for you. For the description, it would be necessary to find something that fits also the other supported version control systems. Something like:
```
 C  for divergence with remote
```

Would it be necessary to distinguish between local being in front of, behind, or split from origin.
Like the tracking branch in git could have newer commits, or the local branch could have newer commits, or both. Which situation do you care most about? All of them?

**Comment by wkentaro** [comment]
I think `wstool` should notify the difference for user in all of these situation.
If there are difference between local and tracking branch, some problems can happen.

**Comment by tkruse** [comment]
maybe this can be closed now?

**Comment by wkentaro** [comment]
I think this issue is related to https://github.com/vcstools/wstool/pull/38 .

**Comment by tkruse** [comment]
ah, ok, we still have not merged
