### ISSUE TITLE
wstool set: resolve uri and scm with --hosted-at option

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#43]
I usually set repository which is hosted at github, and I think wstool can resolve uri and scm by the hosting service name.
So what I want to do is:
```
$ wstool set inbox wkentaro/github -@ github -v master

     Add new elements:
  inbox   	git  https://github.com/wkentaro/github.git   master

Continue: (y)es, (n)o: y
Overwriting /Users/ken/ws/ws_vcstools/.rosinstall
Config changed, remember to run 'wstool update inbox' to update the folder from git
```

This is just inspired by `hub` command.
```
$ # git clone https://github.com/vcstools/wstool.git
$ hub clone vcstools/wstool
```

**Comment by tkruse** [comment]
That's an interesting feature. I wonder if we can make that easier by using ```gh:user/repository```. This would be similar to launchpad URLs.
See: http://doc.bazaar.canonical.com/plugins/en/launchpad-plugin.html

So the usage would be:
```
 wstool set inbox gh:wkentaro/github -v master

     Add new elements:
  inbox     git  https://github.com/wkentaro/github.git   master
```
Though I would probably prefer the ssh URL:   git@github.com:wkentaro/github.git

Can you ask on the buildsystem SIG if users have preferences or other ideas?

**Comment by wkentaro** [comment]
> Though I would probably prefer the ssh URL: git@github.com:wkentaro/github.git

in that case, may be --ssh option is good. (which can be used for other scms as well)

> Can you ask on the buildsystem SIG if users have preferences or other ideas?

https://groups.google.com/forum/#!topic/ros-sig-buildsystem/shXb5R2K_Lw

**Comment by wkentaro** [comment]
closing with lack of interest at SIG.
