### ISSUE TITLE
feature: shell function to change directory in workspace

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#45]
I created shell function to change directory in workspace which is managed by wstool.
Using this function, it is easy to change directory in wstool workspace.
See: https://github.com/wkentaro/wstool_cd

Feature:
- `cd` to workspace's root with no arguments
- `wstool_cd LOCALNAME` to `cd` to repository which is set as `LOCALNAME`
- supports bash and zsh completion

for ROS user, this is useful when doint `cd` to repository which is not yet catkin compiled (when unable to `roscd`).

If possible, I hope this script `wstool_cd.sh` is merged to https://github.com/vcstools/wstool , and let users enable `wstool_cd` just with `source $(which wstool_cd.sh)` in shell after installing wstool.

What do you think?

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
