### ISSUE TITLE
wstool set: new `--update` option to do update after set repository

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#48]
add `--update` option for doing update after `wstool set repo0`.
the behavior is like below:
```
$ wstool set vcstools-wstool https://github.com/vcstools/wstool.git --git -y --update
```
as equivalent to 
```
$ wstool set vcstools-wstool https://github.com/vcstools/wstool.git --git -y
$ wstool update vcstools-wstool
```
see also: https://github.com/vcstools/wstool/issues/46#issuecomment-127539773

I think this option saves time when quickly set only a repository to use.
What do you think about this new option?

**Comment by tkruse** [comment]
I believe that makes sense, also with "-u" as shortcut. It is not a huge improvement, but also not a big code change.

**Comment by wkentaro** [comment]
I sent PR(https://github.com/vcstools/wstool/pull/50).
Please review it when you have time.

**Comment by wkentaro** [comment]
SEE: #50
