### ISSUE TITLE
wstool rm: new `--clean` option to cleanup removed repository

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#49]
add `--clean` option for removing repository after `wstool rm repo0`.
the behavior is like below:

```
$ wstool rm vcstools-wstool --clean
```
as equivalent to 
```
$ wstool rm vcstools-wstool
$ rm -rf vcstools-wstool
```
I think this option saves time when cleaning up the workspace.
What do you think about this new option?

**Comment by tkruse** [comment]
deleting files is dangerous, and so I believe tools should avoid to do this. The simplest example is somebody accidentally using tab completion, getting "--clean" and deleting stuff. Since this stuff might be the work of weeks of development, even if this happens just once, it would be very bad. "--delete" might be a bit more explicit, but even then I am too scared to give this to users.

**Comment by wkentaro** [comment]
why not with confirmation to delete repository?
```
$ wstool rm --clean ros/ros_comm
Overwriting /Users/ken/ws/.rosinstall
Removed entries ['ros/ros_comm']
Remove ros/ros_comm? [y/n]:y
Removed directory ['ros/ros_comm']
```

**Comment by tkruse** [comment]
interaction is usually a pain with tools because they break scriptability. Often this is helped by adding a ```-y``` option to confirm all questions. But in case of deleting, that's really bad.

**Comment by wkentaro** [comment]
rosclean purge supports -y option.
but I understood your idea, and close this issue.

2015年8月5日水曜日、Thibault Kruse<notifications@github.com>さんは書きました:

> interaction is usually a pain with tools because they break scriptability.
> Often this is helped by adding a -y option to confirm all questions. But
> in case of deleting, that's really bad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcstools/wstool/issues/49#issuecomment-127789714>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
