### ISSUE TITLE
easy way to get workspace path?

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#51]
usually, I go to workspace root and run wstool set.
so I wish there was some command to get workspace path easily and quickly.
Now I get it with `wstool info --managed-only | sed -n 1p | awk '{print $2}'` but this takes time
because wstool info collects lots of information.

what I want to do is:

```
$ wstool ws
/Users/ken/ros/indigo/src
$ cd `wstool ws`
$ # cd `wstool info --managed-only | sed -n 1p | awk '{print $2}'`
```

Are there some ways which is equivalent to this?

**Comment by tkruse** [comment]
I guess it would also be possible to use shell scripting to crawl up to a directory with a .rosinstall file. wstool could have someting like ```wstool info --root``` for such purposes.

**Comment by wkentaro** [comment]
I hope this would be officially supported by wstool, not every user to create their own func in shell, so.

**Comment by tkruse** [comment]
A ``--root``` option would be quick and easy to add to wstool info. And a shell function could be added to the wstool autocomplete scripts.

**Comment by wkentaro** [comment]
I see, thanks!

2015年8月5日水曜日、Thibault Kruse<notifications@github.com>さんは書きました:

> A --root` option would be quick and easy to add to wstool info. And a
> shell function could be added to the wstool autocomplete scripts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcstools/wstool/issues/51#issuecomment-127886439>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
I sent PR(#52).
Please review it when you have time.

**Comment by wkentaro** [comment]
Close with #52
