### ISSUE TITLE
pretty formatted yaml file

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#57]
Using pyaml?
https://pypi.python.org/pypi/pyaml
```
> print pyaml.dump(data)
- git:
    local-name: vcstools/wstool
    uri: https://github.com/vcstools/wstool.git
- git:
    local-name: vcstools/vcstools
    uri: https://github.com/vcstools/vcstools.git
    version: master
- git:
    local-name: wkentaro/inbox
    uri: git@github.com:wkentaro/inbox.git
    version: master
- git:
    local-name: wkentaro/pycd
    uri: git@github.com:wkentaro/pycd.git
    version: master
- git:
    local-name: wkentaro/tips
    uri: git@github.com:wkentaro/tips.git
    version: master
...
```

Also I hope the keys (uri, version ..) should appear even if no value.

This makes it easy to read & edit .rosinstall.

**Comment by tkruse** [comment]
-0. .rosinstall is not that hard to read or edit as it is. And it is not to be edited by hand that often.
And not sure if anyone out there wrote tools to parse it without a yaml parser.

**Comment by wkentaro** [comment]
> And not sure if anyone out there wrote tools to parse it without a yaml parser.

What do you mean? Using pyaml is not enough?

**Comment by tkruse** [comment]
No, I mean some people could have written scripts that parse .rosinstall by hand, not using any yaml library. Like parsing using bash script. If we change to pretty yaml, their script would break.

**Comment by wkentaro** [comment]
Hmm, I see.

**Comment by wkentaro** [comment]
formatting rosinstall is still useful because I handle the file with git ot foin the ros package.
(usually for unreleased ros packages) not formatted one is a little hard to read, edit and copy.

I wish this feature will be added as similar problem as (https://github.com/vcstools/wstool/issues/19) .

**Comment by tkruse** [comment]
Can you describe a bit more the changes you usually do to the file? Or what you search in the file when you search?

**Comment by wjwwood** [comment]
I edit `.rosinstall` files by hand all the time, and I know a lot of people who do. Even if they use `wstool` or `rosinstall_generator` to create it initially, they'll often edit it afterwards either to just double check it (read it) or make small tweaks (edit it).

Also the `.rosinstall` format is YAML, so anyone interpreting it without a YAML parser can't reasonably expect their script to work all the time.

That being said, I don't find it hard to read or edit the current formatting. I'd say +0, I don't think it matters that much, but I also don't think it will realistically break anything that shouldn't be broken. If we're really worried about breaking someone, you could ask on ros-users@ to see if anyone would care if it changed to pretty print format.

**Comment by wkentaro** [comment]
**edit**
* add version by using version control (usually search with 'git' and set version 'master')
* rename localname to move repository.
* remove multiple repositories. and after that `rm -rf src/ros_XXX/*`

**search**
I have a lot of packages under jsk-ros-pkg/ like jsk-ros-pkg/jsk_common jsk-rospkg/jsk_recognition,
so I will search jsk-ros-pkg/ in the file to check version, uri, and confirm not duplicate repositories.

**Comment by tkruse** [comment]
Maybe you can locally work with a pretty-printed .rosinstall for a while to see whether it really is better, or not.

**Comment by wkentaro** [comment]
Alright.

**Comment by wkentaro** [comment]
I have been used wstool with pretty formatting function which has below features:

* list formatted yaml
* local names in alphabetical order

I felt this function is helpful to me, because it is
* easy to find repository
* easy to find missing version info, wrong url
* easy to edit localnames because each section is in different line

I think the alphabetical order also prettify the output of wstool info.

**Comment by tkruse** [comment]
The order of localnames is relevant in rosws and rosinstall (which depends on wstool). So changes to that are risky and must be made without impacting rosws.

**Comment by wkentaro** [comment]
At present, wstool rewrite the config file (.rosintall) as new file. And I mean adding sort process before that. Are there some problems on this? (I think I understand what you mean, but this is not so a big change.)

**Comment by tkruse** [comment]
If the sort is outside what is called by rosinstall/rosws, I see no problem.

**Comment by wkentaro** [comment]
so can this feature be supported?

**Comment by tkruse** [comment]
we voted -0, +0, +1, so I guess you can go ahead and implement.
