### ISSUE TITLE
soft link .rosinstall does not work

### ISSUE THREAD

**Issue by wkentaro** [vcstools/wstool#58]
wstool creates .rosinstall as new file so the soft link breaks after wstool set/rm.
the usecase is like:
https://github.com/vcstools/wstool/issues/29#issuecomment-65289108

so, I'm changing to open the realpath of config file. at here:
https://github.com/vcstools/wstool/blob/master/src/wstool/config_yaml.py#L373

any idea?

**Comment by tkruse** [comment]
I thought that use case (switching all repos to a different branch) was covered by having foreach.

Of course the more general use-case is to have arbitrary configurations stored in syminked rosinstall files.

I believe it is usually sane to assume that if the user makes his/her .rosinstall file a symlink, then calls to wstool set should modify the symlinked file, not overwrite the symlink. However, this may not always be the case. In some context, an expert might setup the symlink for many people, and a novice might play around with wstool set and corrupt the global setup. The expert could probably prevent this using access rights. But this should be considered.

Possibly alternatives:
- keep as is
- modify the symlinked files
- cowardly refusing to change a symlinked file
- cowardly refusing to change a symlinked file unless an option like -f --force is used

**Comment by wkentaro** [comment]
>  In some context, an expert might setup the symlink for many people, and a novice might play around with wstool set and corrupt the global setup. The expert could probably prevent this using access rights. But this should be considered.

I think that is in user's responsibility, in that case, the user should copy the file not using symlink.

**Comment by wkentaro** [comment]
also, I'm managing my .rosinstall file using git and sharing with my computers to generate same workspace easily.
at present, I need to copy the file every time when I change it, that is troublesome.

**Comment by tkruse** [comment]
why do you need to copy it, given you manage it with git?

**Comment by wkentaro** [comment]
I copy it to repository which I manage with git and hosted in github.
more specifically, in [dotfiles](https://github.com/wkentaro/dotfiles) directory. 
https://github.com/wkentaro/dotfiles/blob/master/config/ws.rosinstall
https://github.com/wkentaro/dotfiles/blob/master/config/ros-indigo.rosinstall

**Comment by tkruse** [comment]
ah, I see. I thought your workspace was a git repo, like:
```
$ cd ~/ws
$ wstool set hoge /tmp/remote/hoge --git -y
$ git add .rosinstall
$ git commmit ...
$ git push
```
Not sure if a .rosinstall should be in your dotfiles repo.

**Comment by wkentaro** [comment]
yeah, I'm starting this recently. maybe split it to another repository in future.
In that case, the work flow will be like below:
```
$ cd ~/ws
$ git clone https://github.com/wkentaro/rosinstalls .rosinstalls
$ ln -s .rosinstalls/ws.rosinstall .rosinstall
$ wstool update
$ wstool set

$ cd ~/ros/indigo/src
$ git clone https://github.com/wkentaro/rosinstalls .rosinstalls
$ ln -s .roinstalls/ros-indigo.rosinstall .rosinstall
$ wstool update
$ wstool set ..
```
I think I will need to use soft link.

**Comment by wkentaro** [comment]
Using dropbox is another option.
```
$ ln -s ~/Dropbox/rosinstalls/ws.rosinstall .rosinstall
$ ln -s ~/Dropbox/rosinstalls/ros-indigo.rosinstall .rosinstall
```

**Comment by wkentaro** [comment]
can I go ahead and work for this?

**Comment by tkruse** [comment]
Not sure, I gave 4 alternatives in my first response. We did not decide on any of them. @wjwwood : do you have any opinion on this?

**Comment by wjwwood** [comment]
My opinion is that we modify the symlink file. If I symlink a file in place of a normal file, I expect programs to treat it as if it's actually there. I think this what people would expect as well.

As for the read-only symlink file, I think @tkruse's suggestion about access control is the right approach. This is only a good work around though if wstool can operate with the `.rosinstall` file as read-only. I doubt many people have tried that.
