### ISSUE TITLE
more detailed divergence info for wstool info

### ISSUE THREAD

**Issue by NikolausDemmel** [vcstools/wstool#63]
This is a followup from https://github.com/vcstools/wstool/pull/38#issuecomment-139500846 as a new issue.

It would be great if `wstool info` could show more detailed information about divergence between local and tracked remote branch. At the moment, if there is any divergence, a `C` is shown in the status line. What I would like to have is a concise status information telling me if there are unpushed commits, unpulled commits, or both, for example something like `<>`, `<`, or `>` in the status line.

This information would be extremely valuable for my use case where I often have local commits across multiple repos lying around until all repos are ready and can be pushed at the same time. While I have the local commits unpushed, wstool info doesn't tell me if I need to pull / rebase one of my repos to test with the latest upstream changes.

There is a previous discussion about this here: https://github.com/vcstools/wstool/pull/35#issuecomment-124499286

Copy of @tkruse's answer in https://github.com/vcstools/wstool/pull/38#issuecomment-139506190:

> The reasons I gave for not (yet) supporting more detailed information about the divergence types were:
> - would require extention to vcstools API
> - the extended API would be even more complex difficult to support for SVN, HG, BZR
> - It might be sufficient to suport C, then people can check for themselves
> 
> Of course the last point could be handled by just saying the other VCSes do not support a new method, and gracefully return None or something neutral. I understand most ROS code is now using git anyway.
> 
> So basically, it can be hacked rather quickly, but finding and implementing a clean solution would take some effort and thinking.
> 
> The computation time itself was not yet looked at. It would not make wstool info any faster, but probably also not significantly slower (2 shell comands to git per repo that work on local repository).
> 
> If you want to discuss this more, maybe open a new issue on that.
> 
> It might be interesting if something convenient can be hacked using wstool info --yaml or wstool foreach.

**Comment by tkruse** [comment]
Adding more context from https://github.com/vcstools/wstool/pull/35:

Currently wstool info displays a "C" in the status column when the local and the remote version (SHA-ID) differ. That works for all VCSes (git, hg, svn, bzr) based on data accumulated from several calls between wstool and vcstools.

To implement more information about the divergence the following is needed:
- [ ] a design for the output (I suggest: > for local additions, < for remote additions, <> for both, C for unknown divergence in VCSes not supporting divergence details)
- [ ] add a method to the vcstools interface that yields the required information (probably via two calls to ```git rev-list <a> --not <b>```)
- [ ] implement for git, add unit tests
- [ ] implement for SVN (should be trivial), add unit tests
- [ ] implement for tar (no-op)
- [ ] (optionally) implement for hg, add unit tests
- [ ] (optionally) implement for bzr, add unit tests
- [ ] implement logic in wstool to replace 'C' by detailed divergence information when available (Ideally if we can compute that no divergence exist, we can save the two calls to git rev-list). Add unit tests

**Comment by tkruse** [comment]
What worries me most is the API change in vcstools. I cannot yet see the best definition of a function that works well with all VCSes and is quite future-safe. Maybe at one point people will not only want to know local is ahead, but also how many commits it is ahead. Ideally a method could return such information, but it would probably be  structure of some sort (no list or dict, please).

Also note I dont plan to work on this, other than reviewing.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #154.
