### ISSUE TITLE
Version 0.1.9 not working against gitlab

### ISSUE THREAD

**Issue by tompe17** [vcstools/wstool#67]
We have a local gitlab. With version 0.1.9 I get:
```
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.
```

Updating a single repository works.

So what have changed with respect to ssh-git?

**Comment by tkruse** [comment]
Hi,

thanks for the report and sorry about this.

wstool uses git via shell commandos, so when git works in the shell, so should wstool. Nothing recently changed in wstool with respect to shh handling.

Can you also say for which wstool sub command this behavior occurs?

Did you use version 0.1.6 (the most current up to last week) before, or an earlier version?

I have no clue what could be going on in your case.
The only idea I have right now is that some of your repositories have branches tracking branches on other remotes than 'origin', and with 0.1.9 wstool may try to connect to those other remotes, where before it would only use 'origin'. And the failure is with respect to some other remote that may be invalid.

Maybe you can reduce the symptom to just one repository, and paste the output of ```git branch -a```?

**Comment by tompe17** [comment]
Yes, I used 0.1.6 without problem.

I suspect that wstool now do parallell pulls. Is this true? 

I get the same problem with the old one when I do
```
wstool up -j 20
```
I think our gitlab is configured to handle max 10 and when using -j I usually use it with -j 7.

**Comment by tkruse** [comment]
Yes, we changed the default from 10 to unlimited parallel pulls in 896de674768.
The reason was that there seemed no hard reason to default to 10. Do you think we should set the default back to 10?

**Comment by tompe17** [comment]
The default when sshd is installed is 10. I do not know if I can convince the computer support department to increase this...  I have 100 repon in my .rosinstall. I do not know if 100 in parallell is something that will work well.

Either put it back to 10 or have an environment variable for it and make sure -j is working. I tried -j 1 with the new version but that did not work.

Is there a way I can solve this now with the new version?

**Comment by tkruse** [comment]
Ah, I believe 896de67 also introduced a bug that causes -j not to work. Should have unit-tested this.
So I fear there is no workaround for 0.1.9, but maybe we can hurry the release of 0.1.10

**Comment by tkruse** [comment]
So while we wanted to increase the number of threads only for status, diff and info commands, the bug disabled both the default limit of 10 for all other commands, and the -j option.

**Comment by tkruse** [comment]
so #68 should restore the default of 10 for most commands, and reenable -j option. Whether we should also just use 10 for diff, info and status is debatable.

**Comment by cbandera** [comment]
We experienced the same issues. A quick release of the fix in apt-get would be much appreciated! Thanks

**Comment by tkruse** [comment]
It seems it is not possible to install older version via apt-get (becuase the server does not provide them), but in case this might help you, you can install wstool 0.1.6via pip still:
```
pip install -I wstool==0.1.6
```

**Comment by cbandera** [comment]
Perfect, thank you for the hint

**Comment by wjwwood** [comment]
I'll get a new version out this morning.
