### ISSUE TITLE
wstool info shows wrong status when remote default branch changed

### ISSUE THREAD

**Issue by dirk-thomas** [vcstools/wstool#71]
In the following scenario `wstool info` does not indicate the right status.

A rosinstall file contains a git repository without a specific version.
wstool checks out the default branch.
But when the default branch is changed in the remote repository `wstool info` does not indicate that.
Instead it shows that the repository is still "ok" - it does not switch to the new default branch.
Also call `wstool info --fetch` does not help in this case.

Deleting the working copy and cloning the repository again would get the user the new default branch.

**Comment by tkruse** [comment]
That's an interesting case. A change of default branch is rare but not too rare (especially when moving from e.g. indigo-develop to jade-develop.
I believe no native git command would notify the user of such a change, the default branch on remote in git is something only checked checkout time, I believe.

Still where the .rosinstall does not specify any branch, it might be interesting to indicate whether the local branch tracks a non-default remote branch.

The best resource about default branches I found is here:
http://feeding.cloud.geek.nz/posts/setting-default-git-branch-in-bare/
So I guess technically to find out the default branch would be to check the contents of file
```.git/refs/remotes/<remote-name>/HEAD```

How this would be displayed best I don't know.

**Comment by dirk-thomas** [comment]
`vcstool` does this using `git remote show origin` since dirk-thomas/vcstool#21.

**Comment by tkruse** [comment]
I found no other way to do this than calling ```git remote show <remote>``` which means network access. Not sure if we should only use this with option --fetch, or never, or always or add another option.

For displaying, this is only relevant when there is no specified version. Currently we show that as ```Spec: (-)```. Showing the default here with some indication of it being a default could be nice.
