### ISSUE TITLE
Subversion 1.9 unit test failure

### ISSUE THREAD

**Issue by jpgr87** [vcstools/wstool#72]
The wstool unit tests fail when run with subversion 1.9 in a similar manner to the falures described in vcstools/vcstools#105.  The root cause seems to be that subversion now prints "(nonexistent)" instead of "(revision 0)".  The following patch fixes things in the spirit of the vcstools workaround by substituting "nonexistent" in the subversion output with the expected "revision 0":

``` patch
diff -up ./test/local/test_diff_functions_svn.py.svn1.9 ./test/local/test_diff_functions_svn.py
--- ./test/local/test_diff_functions_svn.py.svn1.9      2015-09-16 20:48:48.601333613 -0400
+++ ./test/local/test_diff_functions_svn.py     2015-09-16 20:49:54.681944050 -0400
@@ -36,6 +36,7 @@ import os
 import sys
 from test.io_wrapper import StringIO
 import subprocess
+import re

 import wstool
 import wstool.helpers
@@ -99,6 +100,7 @@ class WstoolDiffSvnTest(AbstractSCMTest)
         modify_svn_repo(clone_path)

     def check_diff_output(self, output):
+        output_fixed = re.sub("\(nonexistent\)", "(revision 0)", output)
         # svn output order varies between versions
         expected = ["""\
 Index: clone/added.txt
@@ -117,7 +119,7 @@ Index: clone/modified.txt
         for snippet in expected:
             for line in snippet.splitlines():
                 # assertIn is not supported in Python2.6
-                self.assertTrue(line in output, output)
+                self.assertTrue(line in output_fixed, output)

     def test_wstool_diff_svn_outside(self):
         """Test diff output for svn when run outside workspace"""
```

If you want to address it in a different way let me know, otherwise I'll open a PR with this change.

**Comment by tkruse** [comment]
looks good, maybe add a comment line about svn 1.9

**Comment by wjwwood** [comment]
This never got made into a pr right?

**Comment by tkruse** [comment]
I think we fixed, was in vcstools: https://github.com/vcstools/vcstools/commit/9af15d963d236

**Comment by wjwwood** [comment]
Oh, I thought there was a similar instance in `wstool` as well. I remember the pr for `vcstools`. @jpgr87 please comment if that's not the case.

**Comment by tkruse** [comment]
oh, wait. You are right. As explained in the description, a test also fils for wstools, and there was never a PR.

**Comment by jpgr87** [comment]
Yeah I forgot to do it.  I'll submit one now.

**Comment by wjwwood** [comment]
Thanks @jpgr87
