### ISSUE TITLE
does wstool interface with the scm tools port reference?

### ISSUE THREAD

**Issue by wegunterjr** [vcstools/wstool#83]
I am trying to use wstool to download something from github, but due to being behind a company firewall, similary to github, I cannot download anything or clone anything (it times out or fails).  Is there any suggestion on what to do?

**Comment by tkruse** [comment]
I am in a rush now, but maybe you could have a look at closed issues of wstool and rosinstall. I think this might have come up in the past, like here:
https://github.com/vcstools/wstool/issues/8

**Comment by tfoote** [comment]
can you clone or download from the command line without wstool?

**Comment by wegunterjr** [comment]
negative.

**Comment by tfoote** [comment]
wstool builds on top of git and other vcs implementations. Until you have the ability to use git and any other vcs directly wstool is not expected to work.

**Comment by wegunterjr** [comment]
right. I am certain of that, but didn't klnow if we had any way of making changes at a higher level (like wstool level).

**Comment by wjwwood** [comment]
There's currently no way of passing information to the underlying vcs programs from `wstool`. I think that if you find you do need to pass something directly to them, we can reopen this issue and find a way to pass the options. My expectation though is that any proxy like settings for these tools will be introduced in user level config files like `~/.gitconfig`.
