### ISSUE TITLE
Ignore user account in URI in .rosinstall 

### ISSUE THREAD

**Issue by 130s** [vcstools/wstool#94]
Wanted to hear opinions before starting to work on a pull request.

For the repositories that I have write access, I tend to prefix the URIs with my github account so that I don't have to type them. But `wstool update` tries to replace the entire cloned source. E.g.:

```
$ wstool update -t ./src
Prepare updating https://github.com/ros-planning/moveit_msgs.git (version jade-devel) to /home/rospasta/cws_planning/src/ros-planning/moveit_msgs
Url https://130s@github.com/ros-planning/moveit_msgs.git does not match https://github.com/ros-planning/moveit_msgs.git requested.
:
$ more src/.rosinstall
- git:
    local-name: ros-planning/moveit_msgs
    uri: https://github.com/ros-planning/moveit_msgs.git
    version: jade-devel
$ git remote -vv
:
origin  https://130s@github.com/ros-planning/moveit_msgs.git (fetch)
origin  https://130s@github.com/ros-planning/moveit_msgs.git (push)
```

Does it make sense to ignore the user account in the URI?

**Comment by wjwwood** [comment]
No I don't think so. Does it make sense to put your username in the URI?

> I tend to prefix the URIs with my github account so that I don't have to type them.

There are plenty of other ways to avoid this:

- https://git-scm.com/docs/git-credential-store
- `url.<base url>.insteadOf`: http://stackoverflow.com/a/22027731/671658
- `~/.netrc`: https://gist.github.com/technoweenie/1072829

**Comment by tfoote** [comment]
You can also force ssh on github using your gitconfig: http://stackoverflow.com/a/36500841/604099 and https://github.com/ros-infrastructure/bloom/issues/256#issuecomment-214927775 outline it well.

**Comment by 130s** [comment]
Thanks for taking time to provide better options. I'll have to try those out but good to close this ticket w/o going further.
